version: 0.0
os: ubuntu
files:
  - source: /home/ubuntu/display-config-access/build/libs/display-config-access-1.0.0.jar
    destination: /home/ubuntu/jars/
hooks:
  ApplicationStop:
    - location: scripts/stop
      timeout: 900
  BeforeInstall:
    - location: scripts/dependencies.sh
      timeout: 900
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 900
  ValidateService:
    - location: scripts/health_check.sh
